version: '3.8'

services:
  backend:
    build: .  # 👈 Use your local Dockerfile
    ports:
      - "3110:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "20007:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

